### ISSUE TITLE
No topbar.

### ISSUE THREAD

**Issue by biig825** [asyafiqe/Rope-docker-headless-vnc-container#2]
![brave_PXyTCXW3kV](https://github.com/user-attachments/assets/2a6b168c-3eeb-408d-8a04-c68b9b3c00b3)
What is wrong with this view? I cannot access the rest of the remote desktop. It only happens when running on certain gpus, other times the resolution is fine and I can interact with the top bar.

**Comment by biig825** [comment]
Maybe this error helps: 

------------------ startup of Xfce4 window manager ------------------
server does not have extension for -dpms option

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.846: Failed to spawn ssh-agent: Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.850: failed to call dbus-update-activation-environment. Output was (null), error was Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.856: Failed to spawn gpg-agent: Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.863: Unable to launch "xfwm4": Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.866: Unable to launch "xfsettingsd": Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.869: Unable to launch "xfce4-panel": Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.872: Unable to launch "Thunar": Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.875: Unable to launch "xfdesktop": Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.879: Unable to launch "xdg-user-dirs-update" (specified by autostart/xdg-user-dirs.desktop): Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.882: Unable to launch "/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1" (specified by autostart/polkit-gnome-authentication-agent-1.desktop): Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.886: Unable to launch "start-pulseaudio-x11" (specified by autostart/pulseaudio.desktop): Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.888: Unable to launch "/usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd" (specified by autostart/xfce4-notifyd.desktop): Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.892: Unable to launch "xfsettingsd" (specified by autostart/xfsettingsd.desktop): Failed to close file descriptor for child process (Operation not permitted)

(xfce4-session:257): xfce4-session-WARNING **: 22:23:50.895: Unable to launch "xiccd" (specified by autostart/xiccd.desktop): Failed to close file descriptor for child process (Operation not permitted)
/usr/bin/startxfce4: X server already running on display :1

**Comment by asyafiqe** [comment]
Sorry I cannot reproduce the error.
Can you try IceWM DE docker variant: 
`asyafiqe/rope_vnc:11.8.0-cudnn8-devel-ubuntu22.04-icewm-Pearl-00-0.8`

**Comment by biig825** [comment]
Hey this kind of helps thank you! However in this image firefox does not open at all. 
![firefox_2niCb5JMZr](https://github.com/user-attachments/assets/29fd518f-50c2-45c6-b339-b6c4f4b2600e)

Thank you for making this project! It's a great idea.

**Comment by asyafiqe** [comment]
Hope this fix the issue:
`asyafiqe/rope_vnc:11.8.0-cudnn8-devel-ubuntu22.04-icewm-Pearl-00-0.8.2`
